package za.co.ultronsport.domain;

public enum AdminActionType {
    USER_APPROVED,
    USER_SUSPENDED,
    USER_REINSTATED,
    EVIDENCE_FLAGGED,
    EVIDENCE_ARCHIVED,
    EVIDENCE_VERIFICATION_HISTORY_VIEWED,
    EVIDENCE_REMOVED,
    LEVELPLAY_RECALCULATED,
    LEVELPLAY_RECALCULATE_ALL,
    USER_VIEWED,
    USER_STATUS_CHANGED,
    MODERATION_NOTE_CREATED,
    VERIFIER_APPROVED,
    VERIFIER_REJECTED,
    ROLE_CHANGED,
    PRIVACY_REQUEST_HANDLED,
    OTHER
}
