package za.co.ultronsport.domain;

public enum NotificationType {
    EVIDENCE_SUBMITTED,
    EVIDENCE_VERIFIED,
    EVIDENCE_REJECTED,
    EVIDENCE_FLAGGED,
    EVIDENCE_ARCHIVED,
    LEVELPLAY_SCORE_CHANGED,
    ACHIEVEMENT_CREATED,
    ATHLETE_PROFILE_UPDATED,
    ORGANISATION_LINKED,
    COACH_PROFILE_UPDATED,
    SYSTEM
}
